sudo: required
language: python
python: 3.7
cache: pip
services:
  - docker
env:
  - ANSIBLE=2.7
  - ANSIBLE=2.8
install:
  - pip install ansible==${ANSIBLE} ansible-lint>=4.0.0 molecule>=2.0 docker git-semver testinfra>=3.0
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
