---
- name: Install SSMTP
  apt:
    name: ssmtp
    state: present
  register: apt_result
  until: apt_result is success
  retries: 3
  delay: 2

- name: Install mailutils
  apt:
    name: mailutils
    state: present
  register: apt_result
  until: apt_result is success
  retries: 3
  delay: 2
